server:
  port: 8081
spring:
  main:
    banner-mode: off
  profiles:
    active: local
  h2.console:
    enabled: true
    path: "/console"
  datasource:
    url: jdbc:h2:file:D:/docker-monitoring--sg/containers-db
  jpa:
    hibernate:
      ddl-auto: update